version: '3.9'

services:
  postgres:
    image: postgres:latest
    container_name: postgres_container
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - .env

  cdp:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: cdp
    depends_on:
      - postgres
    env_file:
      - .env
    ports:
      - "8080:8080"
    networks:
      - app_network

volumes:
  postgres_data:

networks:
  app_network:
